type: google.api.Service
config_version: 3

http:
  rules:
    - selector: superjcd.productservice.v1.ProductService.CreateProduct
      post: /v1/products
    - selector: superjcd.productservice.v1.ProductService.ListProduct
      get: /v1/products
    - selector: superjcd.productservice.v1.ProductService.UpdateProduct
      put: /v1/products
    - selector: superjcd.productservice.v1.ProductService.DeleteProduct
      delete: /v1/products    

    - selector: superjcd.productservice.v1.ProductService.GetAmzProductLatestInfo
      get: /v1/products/info/latest
    - selector: superjcd.productservice.v1.ProductService.AppendAmzProductActiveDetail
      post: /v1/products/info/history/active
    - selector: superjcd.productservice.v1.ProductService.AppendAmzProductInactiveDetail
      post: /v1/products/info/history/inactive

